#!/bin/sh

ip="$1"

result=$(fping -e $ip)

#if [[ $result == *"is unreachable"* ]]; then
if [[ $result != *"is alive"* ]]; then
	echo "%{F#ff0000}∞ ms%{F-}"
	exit
fi

ping=$(echo $result | tail -n 1 | perl -pe 's/.+?(\d+)\.?\d* ms.*/\1/')

if (($ping < 30)); then
	color="#66ff00"
elif (($ping < 80)); then
	color="#66cc00"
elif (($ping < 130)); then
	color="#ccff00"
elif (($ping < 180)); then
	color="#ffff00"
elif (($ping < 230)); then
	color="#ff7700"
elif (($ping < 280)); then
	color="#ff4400"
else
	color="#ff0000"
fi

# echo "%{F$color}$ping""%{F-}"

echo "$ping ms"
