#!/usr/bin/python3

# Adapted from https://github.com/gregmccoy/GPMDP-PlayerInfo/blob/master/playing.py

import json
from os.path import expanduser
import sys
import argparse
from functools import wraps

home = expanduser("~")
parser = argparse.ArgumentParser(formatter_class=argparse.RawTextHelpFormatter, description="Parses and print Google Play Music Desktop Player song info")

def parseJson():
    try:
        with open(home + '/.config/Google Play Music Desktop Player/json_store/playback.json') as f:
            data = f.read()
    except:
        with open(home + '/GPMDP_STORE/playback.json') as f:
            data = f.read()
    return json.loads(data)

def max_chars(char_limit):
    def decorator(func):
        @wraps(func)
        def wrapper(*args, **kwargs):
            s = func(*args, **kwargs)
            if len(s) < char_limit:
                return s
            return s[:max(0, char_limit - 3)] + "..."
        return wrapper
    return decorator

@max_chars(60)
def getSong(data):
    return data['song']['title']

@max_chars(40)
def getAlbum(data):
    return data['song']['album']

@max_chars(30)
def getArtist(data):
    return data['song']['artist']

def convert_time(ms):
    x = ms / 1000
    x % 60
    m, s = divmod(x, 60)
    return "%d:%02d" % (m, s)

def getProgress(data):
    cur = data['time']['current']
    total = data['time']['total']
    return convert_time(cur) + "/" + convert_time(total)

def parseLayout(layout):
    displaystr = ""
    for i in layout:
        if i == 't':
            displaystr += getSong(data)
        elif i == 'a':
            displaystr += getAlbum(data)
        elif i == 'A':
            displaystr += getArtist(data)
        elif i == 'p':
            displaystr += getProgress(data)
        elif i == '-':
            displaystr += " - "
    return displaystr

def run(data, layout):
    displaystr = ""
    if data['playing']:
        displaystr = parseLayout(layout)
    else:
        print('')
        return
    if sys.version[0] == '2':
        print(displaystr.encode('utf-8'))
    else:
        print(displaystr)

parser.add_argument("--layout",
        action="store",
        dest="layout",
        help="t = Song Title\na = Song Album\nA = Artist Name\np = Track time progess\n- = Spacer\nExample: t-a-A-p",
    )

args = parser.parse_args()
data = parseJson()

try:
    run(data, args.layout)
except:
    run(data, "t-a-A-p")


# WID=`xdotool search "Google Play Music Desktop Player" | head -1`
# xdotool windowactivate --sync $WID key space windowactivate $(xdotool getactivewindow)


