require("mappings.misc")
require("mappings.colemak")
require("mappings._coc_nvim")
require("mappings._compe")
require("mappings._fzf_vim")
require("mappings._harpoon")
require("mappings._telescope_nvim")
