#!/bin/sh

# Packages required: i3lock-color, jq
# https://github.com/chrjguill/i3lock-color

# Parse arguments
desired_ws=$1
wallpaper=$2

# Notification manager
notification_manager="dunst"

# Get current workspace
curr_ws=$(i3-msg -t get_workspaces | jq ".[] | select(.focused==true).name" | cut -d"\"" -f2)

# Switch only if not on desired workspace
# This prevents accidental switching if workspace_auto_back_and_forth is enabled in i3
if [[ "$curr_ws" != "$desired_ws" ]]; then
	i3-msg workspace $desired_ws
fi

# Pause notification manager
# (Prevents on-screen notifications)
pkill -u "$USER" -USR1 "$notification_manager"

# Compute parameters
dimensions=$(xdpyinfo | grep dimensions | sed -r 's/^[^0-9]*([0-9]+x[0-9]+).*$/\1/')
width=$( sed -r 's/x[0-9]*$//' <<< $dimensions)
height=$(sed -r 's/^[0-9]*x//' <<< $dimensions)
radius=$((273 * $width / 1920))

# Moon wallpaper
i3lock \
	-n --clock \
	--radius=$radius \
	--indpos="x+(0.4741*w):y+(0.230*h)" \
	--timepos="ix:iy"    --timesize=48 --timecolor=223377ff --timestr="%H:%M:%S" \
	--datepos="tx:ty+40" --datesize=24 --datecolor=223377ff --datestr="%a %m-%d" \
	--line-uses-inside \
	--insidecolor=ffffff55      --ringcolor=ffffff00 \
	--insidevercolor=00000077   --ringvercolor=00000000   --verifcolor=ffffffff --veriftext="analyzing..." \
	--insidewrongcolor=77000099 --ringwrongcolor=77000000 --wrongcolor=ffffffff --wrongtext="self destructing..." \
	--separatorcolor=ffffff77 \
	--color=333344 --image=$wallpaper

# Other options
#	--composite \
#	--line-uses-ring \
#	--insidewrongcolor=ff7777cc \
#	--time-align 1 \ # left align

# Resume notification manager
pkill -u "$USER" -USR2 "$notification_manager"

