#!/bin/sh

# Packages required: i3lock-color, jq
# https://github.com/chrjguill/i3lock-color

# Parse arguments
desired_ws=$1
wallpaper=$2

# Get current workspace
curr_ws=$(i3-msg -t get_workspaces | jq ".[] | select(.focused==true).name" | cut -d"\"" -f2)

# Switch only if not on desired workspace
# This prevents accidental switching if workspace_auto_back_and_forth is enabled in i3
if [[ "$curr_ws" != "$desired_ws" ]]; then
	i3-msg workspace $desired_ws
fi

# Pause notification manager
# (Prevents on-screen notifications)
pkill -u "$USER" -USR1 dunst

# Compute parameters
width=$(xdpyinfo | grep dimensions | perl -ne 'print $_ =~ /(\d+)/')
radius=$((273 * $width / 1920))

# Moon wallpaper
i3lock \
	-n \
	--indpos="x+(0.4741*w):y+(0.230*h)" --radius=$radius \
	--clock --datestr="%a %m-%d" \
	--datepos="x+ix-(0.5*cw):y+iy-(0.5*ch)+40" \
	--textsize=36 --timesize=48 --datesize=24 \
	--timecolor=223377ff --datecolor=223377ff \
	--insidecolor=ffffff55 --line-uses-inside --ringcolor=ffffff00 --separatorcolor=ffffff77 \
	-c 333344 -i $wallpaper

# Other options
#	--timepos="x+ix-(0.5*cw):y+iy-(0.5*ch)" \
#	--composite \
#	--textcolor=223377ff \
#	--insidewrongcolor=ff7777cc \

# Resume notification manager
pkill -u "$USER" -USR2 dunst

