#!/usr/bin/env bash

{
    names="$(pactl list sinks | rg 'Name' | sed 's/^.*: //')"
    descs="$(pactl list sinks | rg 'Description' | sed 's/^.*: //')"
    echo "$names"
    echo "$descs"
    pacmd info | grep 'Default sink' | sed 's/^.*: //'
} | python -c '
import sys
lines = [x.strip() for x in sys.stdin.readlines()]
count = int((len(lines) - 1) / 2)
names = lines[:count]
descs = lines[count:count*2]
curr_name = lines[-1]
idx = next(i for i, x in enumerate(names) if x == curr_name)
next_idx = (idx + 1) % len(names)
print(names[next_idx])
print(descs[next_idx])
' | {
    read -r name
    read -r desc
    pactl set-default-sink "$name"
    notify-send "Default sink changed" "$desc"
}
