#!/usr/bin/env bash

dimensions=$(xdpyinfo | grep dimensions | sed -r 's/^[^0-9]*([0-9]+x[0-9]+).*$/\1/')
width=$( sed -r 's/x[0-9]*$//' <<< $dimensions)
height=$(sed -r 's/^[0-9]*x//' <<< $dimensions)

action=$1

if [ "$action" == "set" ]; then
    i3-msg "resize $@"
    exit
fi

side=$2

if   [ "$side" == "width"  ]; then
    factor=$width
elif [ "$side" == "height" ]; then
    factor=$height
else
    exit
fi

ppt=$3
px=$((factor*ppt/100))
i3-msg "resize $action $side $px px or $ppt ppt"

