require("plugins._lazy_nvim")

do return end


require("plugins._packer_nivm")

require("plugins._impatient_nvim")
require("plugins._filetype_nvim")

require("plugins._coc_nvim")
require("plugins._completion_nvim")
require("plugins._coq_nvim")
require("plugins._gitsigns_nvim")
require("plugins._indent_blankline_nvim")
require("plugins._kommentary")
require("plugins._leap_nvim")
require("plugins._lightspeed_nvim")
require("plugins._nvim_autopairs")
require("plugins._nvim_compe")
require("plugins._nvim_lspconfig")
require("plugins._nvim_lspfuzzy")
require("plugins._nvim_quantum")
require("plugins._nvim_scrollbar")
require("plugins._nvim_scrollview")
require("plugins._nvim_treesitter")
require("plugins._tcomment_vim")
require("plugins._telescope_nvim")
require("plugins._ultisnips")
require("plugins._vim_gutentags")
require("plugins._vim_peekaboo")
require("plugins._vim_polyglot")
require("plugins._vim_slime")
require("plugins._vim_vsnip")
require("plugins._vimtex")
require("plugins._virt_column_nvim")
