export CLASSPATH=""
export FILTER_BRANCH_SQUELCH_WARNING=1
export FZF_DEFAULT_COMMAND='fd --type f'
export GOPATH="$HOME/.cache/go"
# export JUPYTERLAB_DIR="$HOME/.local/share/jupyter/lab"
export MANPAGER="sh -c 'col -bx | bat -l man -p'"
export PATH="$PATH:$HOME/.cabal/bin"
export PATH="$PATH:$HOME/.cargo/bin"
export PATH="$PATH:$HOME/.local/bin"
export RIPGREP_CONFIG_PATH="$HOME/.config/ripgrep/rc"
# export RUST_SRC_PATH="$(rustc --print sysroot)/lib/rustlib/src/rust/src"
export RUST_SRC_PATH="$HOME/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src"
export TF_CPP_MIN_LOG_LEVEL=2
