ZSH_USR_SHARE="/cvmfs/soft.computecanada.ca/gentoo/2020/usr/share/zsh"
ZSH_FUNCTIONS_PATH="$ZSH_USR_SHARE/5.8/functions"

export FPATH="$FPATH"\
":$HOME/.local/share/zsh/site-functions"\
":$ZSH_USR_SHARE/site-functions"\
":$ZSH_FUNCTIONS_PATH/Calendar"\
":$ZSH_FUNCTIONS_PATH/Chpwd"\
":$ZSH_FUNCTIONS_PATH/Completion"\
":$ZSH_FUNCTIONS_PATH/Completion/AIX"\
":$ZSH_FUNCTIONS_PATH/Completion/Base"\
":$ZSH_FUNCTIONS_PATH/Completion/bashcompinit"\
":$ZSH_FUNCTIONS_PATH/Completion/BSD"\
":$ZSH_FUNCTIONS_PATH/Completion/compaudit"\
":$ZSH_FUNCTIONS_PATH/Completion/compdump"\
":$ZSH_FUNCTIONS_PATH/Completion/compinit"\
":$ZSH_FUNCTIONS_PATH/Completion/compinstall"\
":$ZSH_FUNCTIONS_PATH/Completion/Cygwin"\
":$ZSH_FUNCTIONS_PATH/Completion/Darwin"\
":$ZSH_FUNCTIONS_PATH/Completion/Debian"\
":$ZSH_FUNCTIONS_PATH/Completion/Linux"\
":$ZSH_FUNCTIONS_PATH/Completion/Mandriva"\
":$ZSH_FUNCTIONS_PATH/Completion/openSUSE"\
":$ZSH_FUNCTIONS_PATH/Completion/Redhat"\
":$ZSH_FUNCTIONS_PATH/Completion/Solaris"\
":$ZSH_FUNCTIONS_PATH/Completion/Unix"\
":$ZSH_FUNCTIONS_PATH/Completion/X"\
":$ZSH_FUNCTIONS_PATH/Completion/Zsh"\
":$ZSH_FUNCTIONS_PATH/Exceptions"\
":$ZSH_FUNCTIONS_PATH/Math"\
":$ZSH_FUNCTIONS_PATH/MIME"\
":$ZSH_FUNCTIONS_PATH/Misc"\
":$ZSH_FUNCTIONS_PATH/Newuser"\
":$ZSH_FUNCTIONS_PATH/Prompts"\
":$ZSH_FUNCTIONS_PATH/TCP"\
":$ZSH_FUNCTIONS_PATH/VCS_Info"\
":$ZSH_FUNCTIONS_PATH/Zftp"\
":$ZSH_FUNCTIONS_PATH/Zle"\
""
