#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.
menuentry "Windows 10" --class os {
    insmod ntfs
    search --no-floppy --set=root --fs-uuid BCB2DA24B2D9E346
    ntldr /bootmgr
}
